# site settings
remote_theme: Forty
baseurl: "/forty-jekyll-theme"
markdown: kramdown
permalink: pretty
title: CODER
subtitle: BY NIGHT DOCTOR BY DAY
email: muindenthusi@gmail.com
description: The medical doctor<br /> who actually codes!
 # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Muinde Nthusi
street_address: P.O. Box 11427 - 00100
city: General Post Office Nairobi
zip_code: 00100
country: The Republic of Kenya
phone: +254 (716) 30-1035

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/nthusi
  GitLab:
  Google-Plus: mailto:muindenthusi@gmail.com
  Instagram: https://instagram.com/muindenthusi/
  LinkedIn: https://linkedin.com/in/muinde-nthusi-b86265205/
  Twitter: https://twitter.com/andrewbanchich
  Facebook:
  Slack: https://app.slack.com/client/T07494ETL7M/D073ULTMW4X

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
